name: CMake Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: PRO self-hosted
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.20.0'

    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: cmake -S . -B build

    - name: Build with CMake
      run: cmake --build build

    - name: Run tests
      run: ctest --test-dir build
